name=unio_EEPROM
version=0.1.0
author=HongLiang Qian
maintainer=HongLiang <1722576182@qq.com>
sentence=Minimal production-ready MicroChip uni/o eeprom library for ESP32-S3.
paragraph=Provides read/write for uni/o eeprom.11LC040 is tested.
category=uni/o
url=https://github.com/qianhl2002/unio_EEPROM
architectures=esp32
includes=unio_EEPROM.h
